# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemgraphMcpServer < Formula
  desc "Memgraph MCP Server for Claude Code"
  homepage "https://github.com/mgorunuch/memgraph-mcp-server"
  version "0.1.2"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgorunuch/memgraph-mcp-server/releases/download/v0.1.2/memgraph-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "e2ad09a292e1786662215b899be708eb66292af40ed764b97e3907115e2543ec"

      def install
        bin.install "memgraph-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgorunuch/memgraph-mcp-server/releases/download/v0.1.2/memgraph-mcp-server_Darwin_arm64.tar.gz"
      sha256 "527b3f36ae1c011b2edcec3e2b86f7676a51614bd503f3647081dcd4052a7362"

      def install
        bin.install "memgraph-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/memgraph-mcp-server/releases/download/v0.1.2/memgraph-mcp-server_Linux_x86_64.tar.gz"
      sha256 "44130d158f0edc9f3093ec16cf466f445f2badbd5f7c3a339c62813701641f14"
      def install
        bin.install "memgraph-mcp-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/memgraph-mcp-server/releases/download/v0.1.2/memgraph-mcp-server_Linux_arm64.tar.gz"
      sha256 "7c4c5afdcaf49506c5642772370ed42ae7056f554b870ff6dd9a8360ea84344f"
      def install
        bin.install "memgraph-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/memgraph-mcp-server --version"
  end
end
